/** @type {import('tailwindcss').Config} */
// Modern Skeuomorphic Slate & Steel — Sajag Tactical Command
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#0c0e10',
        'surface-container': '#14181b',
        'secondary-fixed': '#cbd5e1',
        'on-secondary-fixed': '#0f172a',
        primary: '#f8fafc',
        secondary: '#94a3b8',
        'inverse-surface': '#cbd5e1',
        'error-container': '#93000a',
        'surface-variant': '#1e293b',
        surface: '#0f172a',
        'primary-container': '#e2e8f0',   // Steel/slate accent
        'outline-variant': '#334155',
        'on-primary-fixed-variant': '#334155',
        'on-tertiary-container': '#64748b',
        'surface-bright': '#334155',
        error: '#ffb4ab',
        'tertiary-fixed': '#cbd5e1',
        'on-tertiary': '#1e293b',
        'secondary-fixed-dim': '#94a3b8',
        'primary-fixed': '#cbd5e1',
        'surface-container-highest': '#1e293b',
        'on-primary-container': '#0f172a',
        'surface-container-lowest': '#020617',
        'surface-container-low': '#0f172a',
        'surface-container-high': '#1e293b',
        'on-secondary-container': '#94a3b8',
        'inverse-on-surface': '#0f172a',
        'inverse-primary': '#475569',
        'on-error': '#690005',
        'tertiary-container': '#cbd5e1',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#0f172a',
        tertiary: '#f8fafc',
        'on-surface': '#cbd5e1',
        'on-background': '#cbd5e1',
        'secondary-container': '#1e293b',
        'on-primary': '#0f172a',
        outline: '#475569',
        'on-secondary-fixed-variant': '#1e293b',
        'surface-tint': '#e2e8f0',
        'on-surface-variant': '#94a3b8',
        'on-secondary': '#0f172a',
        'primary-fixed-dim': '#94a3b8',
        background: '#090d10',
        warning: '#f5b544',
        // Semantic colors (green remains for online/success)
        success: '#39ff6a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-md': '16px',
        unit: '4px',
        'stack-sm': '8px',
        'container-padding-desktop': '40px',
        'container-padding-mobile': '20px',
        'stack-lg': '32px',
        gutter: '24px',
      },
      fontFamily: {
        poppins: ['Poppins', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
